# commands to specify testing environments
language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - python setup.py -q install

# command to run tests
script:
  python -m unittest discover -p '*_test.py'
